
import { NextResponse } from 'next/server';

/**
 * @description API Route to demonstrate server-side capabilities.
 * This function runs exclusively on the server (Node.js environment).
 * @returns {Promise<NextResponse>} A JSON response containing server-specific information.
 */
export async function GET(request: Request) {
  // This is server-side Node.js code.
  // 1. Get the current timestamp directly from the server's system.
  const serverTime = new Date();

  // 2. Get server region information (Vercel provides this via an environment variable).
  // This is a clear example of data only available on the backend.
  const serverRegion = process.env.VERCEL_REGION || 'Development Server';

  // 3. Construct the JSON payload.
  const data = {
    message: "This response was generated by Node.js on the server!",
    serverTimestamp: serverTime.toISOString(),
    serverRegion: serverRegion,
    note: "This proves backend code execution within the Next.js framework."
  };

  // 4. Return the data as a JSON response.
  return NextResponse.json(data);
}
